/-
Copyright (c) 2026 The iut contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The iut contributors
-/
import Iut.Concrete.LocalTheory
import Iut.Concrete.ThetaLocalConstruct.EmbedCompletion
import Iut.Cor312.ThetaData.AdmissiblePrime

/-!
# The normalized valuation `ord_p` on completions, and its base change

The valuation `Iut.ordp K v x = −log‖x‖/([K_v : ℚ_p]·log p)` of `Iut.Concrete.LocalTheory` is
computed from the `Valued` structure of the completion: for `Valued.v x = exp m`,
`‖x‖ = (p^{f_v})^m` (`Iut.norm_eq_zpow_of_valued`), hence `ord_p(x) = −m/e_v`
(`Iut.ordp_eq_of_valued`). Consequences:

* `ord_p` is invariant under the comparison map `k_w → K_v` for `v ∣ w`
  (`Iut.ordp_embedCompletion`), from `e_v = e_w·e(v/w)` (`Iut.ramIdx_eq_mul`);
* for a uniformizer `π` of `k_w` in the sense of `TateCurvesTheta.IsUniformizer`,
  `Valued.v π = exp (−1)`, so the normalized order `orderNat` of a Tate parameter `q` gives
  `ord_p(q) = orderNat/e_w` (`Iut.ordp_tateParameter`);
* the fundamental identity `∑_{v ∣ w} e_v f_v = [K : k]·e_w f_w` (`Iut.sum_localDeg_liesOver`).
-/

namespace Iut

open NumberField IsDedekindDomain WithZero TateCurvesTheta
open scoped WithZero

noncomputable section

/-! ### The prime below a place, and the norm on the completion -/

section Single

variable {K : Type*} [Field K] [NumberField K]

/-- The prime of `ℤ` below the prime of a finite place is generated by its residue
characteristic. -/
lemma under_int_eq (v : FinitePlace K) :
    v.maximalIdeal.asIdeal.under ℤ = Ideal.span {(residueChar v : ℤ)} := by
  set P := v.maximalIdeal.asIdeal
  have hp : (residueChar v).Prime := residueChar_prime v
  haveI : CharP (𝓞 K ⧸ P) (residueChar v) := ringChar.charP _
  have hmem : (residueChar v : ℤ) ∈ P.under ℤ := by
    rw [Ideal.under_def, Ideal.mem_comap, map_natCast]
    exact Ideal.natCast_mem_of_charP_quotient (residueChar v) P
  have hle : Ideal.span {(residueChar v : ℤ)} ≤ P.under ℤ := by
    rw [Ideal.span_le, Set.singleton_subset_iff]
    exact hmem
  haveI hprime : (Ideal.span {(residueChar v : ℤ)}).IsPrime :=
    (Ideal.span_singleton_prime (by exact_mod_cast hp.ne_zero)).mpr
      (Nat.prime_iff_prime_int.mp hp)
  have hmax : (Ideal.span {(residueChar v : ℤ)}).IsMaximal :=
    IsPrime.to_maximal_ideal (by
      rw [Ne, Ideal.span_singleton_eq_bot]
      exact_mod_cast hp.ne_zero)
  haveI : (P.under ℤ).IsPrime := Ideal.comap_isPrime _ _
  exact (hmax.eq_of_le (Ideal.IsPrime.ne_top inferInstance) hle).symm

/-- The prime of `ℤ` below a finite place is nonzero. -/
lemma under_int_ne_bot (v : FinitePlace K) : v.maximalIdeal.asIdeal.under ℤ ≠ ⊥ := by
  rw [under_int_eq, Ne, Ideal.span_singleton_eq_bot]
  exact_mod_cast (residueChar_prime v).ne_zero

/-- The prime of `ℤ` below a finite place is maximal. -/
lemma under_int_isMaximal (v : FinitePlace K) : (v.maximalIdeal.asIdeal.under ℤ).IsMaximal := by
  have hp : (residueChar v).Prime := residueChar_prime v
  rw [under_int_eq]
  haveI : (Ideal.span {(residueChar v : ℤ)}).IsPrime :=
    (Ideal.span_singleton_prime (by exact_mod_cast hp.ne_zero)).mpr
      (Nat.prime_iff_prime_int.mp hp)
  exact IsPrime.to_maximal_ideal (by
    rw [Ne, Ideal.span_singleton_eq_bot]
    exact_mod_cast hp.ne_zero)

/-- The prime of a finite place lies over `(p)`, `p` its residue characteristic. -/
lemma liesOver_span_residueChar (v : FinitePlace K) :
    v.maximalIdeal.asIdeal.LiesOver (Ideal.span {(residueChar v : ℤ)}) :=
  ⟨(under_int_eq v).symm⟩

/-- `N(𝔭_v) = p^{f_v}`. -/
lemma absNorm_eq_pow_residueChar (v : FinitePlace K) :
    Ideal.absNorm v.maximalIdeal.asIdeal = residueChar v ^ inertDeg K v := by
  haveI := liesOver_span_residueChar v
  exact (Ideal.pow_inertiaDeg (residueChar v) v.maximalIdeal.asIdeal).symm

/-- `f_v > 0`. -/
lemma inertDeg_pos' (v : FinitePlace K) : 0 < inertDeg K v :=
  Ideal.inertiaDeg_pos v.maximalIdeal.asIdeal ℤ

/-- `e_v > 0`. -/
lemma ramIdx_pos' (v : FinitePlace K) : 0 < ramIdx K v :=
  Ideal.ramificationIdx_pos v.maximalIdeal.asIdeal ℤ

/-- The norm of an element of valuation `exp m` is `(p^{f_v})^m`. -/
lemma norm_eq_zpow_of_valued (v : FinitePlace K) (x : completionAt K v) (m : ℤ)
    (hx : Valued.v x = exp m) :
    ‖x‖ = ((residueChar v : ℝ) ^ inertDeg K v) ^ m := by
  rw [FinitePlace.norm_def, hx, WithZeroMulInt.toNNReal_neg_apply _ exp_ne_zero]
  have h : (WithZero.unzero (exp_ne_zero (a := m))).toAdd = m := rfl
  rw [h, NNReal.coe_zpow, NNReal.coe_natCast, absNorm_eq_pow_residueChar, Nat.cast_pow]

/-- `ord_p(x) = −m/e_v` for `Valued.v x = exp m`. -/
lemma ordp_eq_of_valued (v : FinitePlace K) (x : completionAt K v) (m : ℤ)
    (hx : Valued.v x = exp m) :
    ordp K v x = -(m : ℝ) / ramIdx K v := by
  have hp : (residueChar v).Prime := residueChar_prime v
  have hlog : 0 < Real.log (residueChar v) := Real.log_pos (by exact_mod_cast hp.one_lt)
  have hf : (0 : ℝ) < inertDeg K v := by exact_mod_cast inertDeg_pos' v
  unfold ordp localDeg
  rw [norm_eq_zpow_of_valued v x m hx, Real.log_zpow, Real.log_pow, Nat.cast_mul]
  field_simp

/-- `ord_p(x^m) = m·ord_p(x)`. -/
lemma ordp_pow' (v : FinitePlace K) (x : completionAt K v) (m : ℕ) :
    ordp K v (x ^ m) = m * ordp K v x := by
  unfold ordp
  rw [norm_pow, Real.log_pow]
  ring

/-- `ord_p(x) ≥ 0` for `‖x‖ ≤ 1`. -/
lemma ordp_nonneg_of_norm_le_one (v : FinitePlace K) (x : completionAt K v) (hx : ‖x‖ ≤ 1) :
    0 ≤ ordp K v x := by
  have hp : (residueChar v).Prime := residueChar_prime v
  have hlog : 0 < Real.log (residueChar v) := Real.log_pos (by exact_mod_cast hp.one_lt)
  have hd : (0 : ℝ) < localDeg K v := by
    unfold localDeg
    exact_mod_cast Nat.mul_pos (ramIdx_pos' v) (inertDeg_pos' v)
  unfold ordp
  apply div_nonneg _ (mul_pos hd hlog).le
  rw [neg_nonneg]
  exact Real.log_nonpos (norm_nonneg _) hx

end Single

/-! ### Base change of `ord_p` -/

section Extension

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]

/-- `𝓞_K` is torsion-free over `𝓞_k`. -/
instance ringOfIntegers_isTorsionFree : Module.IsTorsionFree (𝓞 k) (𝓞 K) where
  isSMulRegular r hr a b hab := by
    have hr0 : algebraMap (𝓞 k) (𝓞 K) r ≠ 0 :=
      (map_ne_zero_iff _ algebraMap_ringOfIntegers_injective).mpr hr.ne_zero
    simp only [Algebra.smul_def] at hab
    exact mul_left_cancel₀ hr0 hab

variable {v : FinitePlace K} {w : FinitePlace k} (hvw : FinitePlace.LiesOver v w)
include hvw

/-- The prime of `ℤ` below `v` is the prime below `w`. -/
lemma under_int_eq_under_int : v.maximalIdeal.asIdeal.under ℤ = w.maximalIdeal.asIdeal.under ℤ := by
  haveI : v.maximalIdeal.asIdeal.LiesOver w.maximalIdeal.asIdeal := hvw
  rw [← Ideal.under_under (B := 𝓞 k) v.maximalIdeal.asIdeal,
    ← Ideal.over_def v.maximalIdeal.asIdeal w.maximalIdeal.asIdeal]

/-- Places over each other have the same residue characteristic. -/
lemma residueChar_eq_of_liesOver : residueChar v = residueChar w := by
  have h := under_int_eq_under_int hvw
  rw [under_int_eq, under_int_eq, Ideal.span_singleton_eq_span_singleton] at h
  have h' := Int.natAbs_eq_iff_associated.mpr h
  simpa using h'

/-- The ramification index `e(v/w)` is nonzero. -/
lemma relRamIdx_ne_zero : relRamIdx v w ≠ 0 := ramificationIdx'_ne_zero hvw

/-- `e_v = e_w · e(v/w)`. -/
lemma ramIdx_eq_mul : ramIdx K v = ramIdx k w * relRamIdx v w := by
  haveI : v.maximalIdeal.asIdeal.LiesOver w.maximalIdeal.asIdeal := hvw
  have hp : v.maximalIdeal.asIdeal.under ℤ ≠ ⊥ := under_int_ne_bot v
  haveI : w.maximalIdeal.asIdeal.LiesOver (v.maximalIdeal.asIdeal.under ℤ) :=
    Ideal.LiesOver.tower_bot v.maximalIdeal.asIdeal w.maximalIdeal.asIdeal _
  have h1 : ramIdx K v = (v.maximalIdeal.asIdeal.under ℤ).ramificationIdx' v.maximalIdeal.asIdeal :=
    (Ideal.ramificationIdx'_eq_ramificationIdx _ v.maximalIdeal.asIdeal hp).symm
  have h2 : ramIdx k w =
      (v.maximalIdeal.asIdeal.under ℤ).ramificationIdx' w.maximalIdeal.asIdeal := by
    have := (Ideal.ramificationIdx'_eq_ramificationIdx (w.maximalIdeal.asIdeal.under ℤ)
      w.maximalIdeal.asIdeal (under_int_ne_bot w)).symm
    rw [under_int_eq_under_int hvw]
    exact this
  rw [h1, h2]
  exact Ideal.ramificationIdx'_algebra_tower' _ w.maximalIdeal.asIdeal v.maximalIdeal.asIdeal

/-- The residue degree `f(v/w)` of `v` over `w`. -/
abbrev relInertDeg (v : FinitePlace K) (w : FinitePlace k) : ℕ :=
  w.maximalIdeal.asIdeal.inertiaDeg' v.maximalIdeal.asIdeal

/-- `f_v = f_w · f(v/w)`. -/
lemma inertDeg_eq_mul : inertDeg K v = inertDeg k w * relInertDeg v w := by
  haveI : v.maximalIdeal.asIdeal.LiesOver w.maximalIdeal.asIdeal := hvw
  haveI : w.maximalIdeal.asIdeal.LiesOver (v.maximalIdeal.asIdeal.under ℤ) :=
    Ideal.LiesOver.tower_bot v.maximalIdeal.asIdeal w.maximalIdeal.asIdeal _
  haveI : (v.maximalIdeal.asIdeal.under ℤ).IsMaximal := under_int_isMaximal v
  haveI : w.maximalIdeal.asIdeal.IsMaximal :=
    w.maximalIdeal.isPrime.isMaximal w.maximalIdeal.ne_bot
  haveI : v.maximalIdeal.asIdeal.IsMaximal :=
    v.maximalIdeal.isPrime.isMaximal v.maximalIdeal.ne_bot
  have h1 : inertDeg K v = (v.maximalIdeal.asIdeal.under ℤ).inertiaDeg' v.maximalIdeal.asIdeal :=
    (Ideal.inertiaDeg'_eq_inertiaDeg _ v.maximalIdeal.asIdeal).symm
  have h2 : inertDeg k w = (v.maximalIdeal.asIdeal.under ℤ).inertiaDeg' w.maximalIdeal.asIdeal := by
    haveI : (w.maximalIdeal.asIdeal.under ℤ).IsMaximal := under_int_isMaximal w
    have := (Ideal.inertiaDeg'_eq_inertiaDeg (w.maximalIdeal.asIdeal.under ℤ)
      w.maximalIdeal.asIdeal).symm
    rw [under_int_eq_under_int hvw]
    exact this
  rw [h1, h2]
  exact Ideal.inertiaDeg'_algebra_tower _ w.maximalIdeal.asIdeal v.maximalIdeal.asIdeal

/-- `[K_v : ℚ_p] = [k_w : ℚ_p] · e(v/w) f(v/w)`. -/
lemma localDeg_eq_mul : localDeg K v = localDeg k w * (relRamIdx v w * relInertDeg v w) := by
  unfold localDeg
  rw [ramIdx_eq_mul hvw, inertDeg_eq_mul hvw]
  ring

/-- **`ord_p` is invariant under the comparison map** `k_w → K_v`. -/
theorem ordp_embedCompletion (y : localCompletion w) :
    ordp K v (embedCompletion hvw y) = ordp k w y := by
  by_cases hy : y = 0
  · subst hy
    simp [ordp, norm_zero, Real.log_zero]
  have hy' : Valued.v y ≠ 0 := (Valuation.ne_zero_iff _).2 hy
  set m : ℤ := log (Valued.v y)
  have hm : Valued.v y = exp m := (exp_log hy').symm
  have hm' : Valued.v (embedCompletion hvw y) = exp ((relRamIdx v w : ℤ) * m) := by
    rw [valued_embedCompletion, hm, ← exp_nsmul, nsmul_eq_mul]
  rw [ordp_eq_of_valued v _ _ hm', ordp_eq_of_valued w y m hm, ramIdx_eq_mul hvw]
  have he : (relRamIdx v w : ℝ) ≠ 0 := by exact_mod_cast relRamIdx_ne_zero hvw
  push_cast
  field_simp

end Extension

/-! ### The fundamental identity for the places over `w` -/

section Sum

variable {k K : Type*} [Field k] [NumberField k] [Field K] [NumberField K] [Algebra k K]

/-- `∑_{v ∣ w} e_v f_v = [K : k] · e_w f_w`, for any finset `s` of places of `K` consisting of
exactly the places over `w`. -/
theorem sum_localDeg_liesOver (w : FinitePlace k) (s : Finset (FinitePlace K))
    (hs : ∀ v, v ∈ s ↔ FinitePlace.LiesOver v w) :
    ∑ v ∈ s, localDeg K v = Module.finrank k K * localDeg k w := by
  classical
  haveI : w.maximalIdeal.asIdeal.IsMaximal :=
    w.maximalIdeal.isPrime.isMaximal w.maximalIdeal.ne_bot
  have hp0 : w.maximalIdeal.asIdeal ≠ ⊥ := w.maximalIdeal.ne_bot
  have hsum := Ideal.sum_ramification_inertia (𝓞 K) k K hp0 (p := w.maximalIdeal.asIdeal)
  have hbij : ∑ v ∈ s, (relRamIdx v w * relInertDeg v w) =
      ∑ P ∈ IsDedekindDomain.primesOverFinset w.maximalIdeal.asIdeal (𝓞 K),
        w.maximalIdeal.asIdeal.ramificationIdx' P * w.maximalIdeal.asIdeal.inertiaDeg' P := by
    refine Finset.sum_bij (fun v _ => v.maximalIdeal.asIdeal) ?_ ?_ ?_ ?_
    · intro v hv
      haveI : v.maximalIdeal.asIdeal.LiesOver w.maximalIdeal.asIdeal := (hs v).mp hv
      exact (IsDedekindDomain.mem_primesOverFinset_iff hp0 (𝓞 K)).mpr ⟨inferInstance, inferInstance⟩
    · intro v₁ _ v₂ _ h
      exact (FinitePlace.maximalIdeal_inj _ _).mp (HeightOneSpectrum.ext h)
    · intro P hP
      obtain ⟨hprime, hover⟩ := (IsDedekindDomain.mem_primesOverFinset_iff hp0 (𝓞 K)).mp hP
      have hne : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hp0 P
      refine ⟨FinitePlace.mk ⟨P, hprime, hne⟩, ?_, ?_⟩
      · rw [hs]
        unfold FinitePlace.LiesOver
        rw [FinitePlace.maximalIdeal_mk]
        exact hover
      · rw [FinitePlace.maximalIdeal_mk]
    · intro v _
      rfl
  have h : ∀ v ∈ s, localDeg K v = localDeg k w * (relRamIdx v w * relInertDeg v w) :=
    fun v hv => localDeg_eq_mul ((hs v).mp hv)
  rw [Finset.sum_congr rfl h, ← Finset.mul_sum, hbij, hsum, mul_comm]

end Sum

/-! ### Uniformizers and Tate parameters -/

section Uniformizer

variable {k : Type*} [Field k] [NumberField k] (w : FinitePlace k)

/-- A uniformizer in the sense of `TateCurvesTheta.IsUniformizer` has valuation `exp (−1)`. -/
lemma valued_eq_of_isUniformizer {π : localCompletion w} (hπ : IsUniformizer π) :
    Valued.v π = exp (-1 : ℤ) := by
  -- an element of valuation `exp (-1)`
  obtain ⟨π₀, hπ₀⟩ := w.maximalIdeal.valuation_exists_uniformizer' (K := k)
  have hπ₀' : Valued.v (FinitePlace.embedding w.maximalIdeal π₀ : localCompletion w) =
      exp (-1 : ℤ) := by
    rw [FinitePlace.embedding_apply, HeightOneSpectrum.valuedAdicCompletion_eq_valuation', hπ₀]
  have hN : (1 : ℝ) < (residueChar w : ℝ) ^ inertDeg k w := by
    have hp : (residueChar w).Prime := residueChar_prime w
    exact one_lt_pow₀ (by exact_mod_cast hp.one_lt) (inertDeg_pos' w).ne'
  have hN0 : (0 : ℝ) < (residueChar w : ℝ) ^ inertDeg k w := zero_lt_one.trans hN
  have hπ' : Valued.v π ≠ 0 := (Valuation.ne_zero_iff _).2 hπ.ne_zero
  set m : ℤ := log (Valued.v π)
  have hm : Valued.v π = exp m := (exp_log hπ').symm
  have hnorm : ‖π‖ = ((residueChar w : ℝ) ^ inertDeg k w) ^ m := norm_eq_zpow_of_valued w π m hm
  have hm0 : m < 0 := by
    have := hπ.norm_lt_one
    rw [hnorm, zpow_lt_one_iff_right₀ hN] at this
    exact this
  have hunit : (FinitePlace.embedding w.maximalIdeal π₀ : localCompletion w) ≠ 0 := by
    intro h
    rw [h, map_zero] at hπ₀'
    exact exp_ne_zero hπ₀'.symm
  obtain ⟨n, hn⟩ := hπ.generates (Units.mk0 _ hunit)
  rw [Units.val_mk0, norm_eq_zpow_of_valued w _ _ hπ₀', hnorm, ← zpow_mul] at hn
  have hmn : (-1 : ℤ) = m * n := zpow_right_injective₀ hN0 hN.ne' hn
  have hm1 : m = -1 := by
    have hunit : IsUnit m := IsUnit.of_mul_eq_one (-n) (by rw [mul_neg, ← hmn]; norm_num)
    rcases Int.isUnit_iff.mp hunit with h | h
    · omega
    · exact h
  rw [hm, hm1]

variable {w}

/-- The valuation of a Tate parameter is `exp (−orderNat)`, for the normalized order with
respect to a uniformizer. -/
lemma valued_tateParameter_q (t : TateParameter (localCompletion w)) {π : localCompletion w}
    (hπ : IsUniformizer π) :
    Valued.v (t.q : localCompletion w) = exp (-((t.toOrdered hπ).orderNat : ℤ)) := by
  have hq : (t.q : localCompletion w) ≠ 0 := t.q.ne_zero
  have hq' : Valued.v (t.q : localCompletion w) ≠ 0 := (Valuation.ne_zero_iff _).2 hq
  set m : ℤ := log (Valued.v (t.q : localCompletion w))
  have hm : Valued.v (t.q : localCompletion w) = exp m := (exp_log hq').symm
  have hN : (1 : ℝ) < (residueChar w : ℝ) ^ inertDeg k w := by
    have hp : (residueChar w).Prime := residueChar_prime w
    exact one_lt_pow₀ (by exact_mod_cast hp.one_lt) (inertDeg_pos' w).ne'
  have h1 := t.norm_q_eq_pow_orderNat hπ
  rw [norm_eq_zpow_of_valued w _ m hm,
    norm_eq_zpow_of_valued w π _ (valued_eq_of_isUniformizer w hπ)] at h1
  set N : ℝ := (residueChar w : ℝ) ^ inertDeg k w with hN'
  rw [← zpow_natCast, ← zpow_mul] at h1
  have := zpow_right_injective₀ (zero_lt_one.trans hN) hN.ne' h1
  rw [hm, this]
  congr 1
  ring

/-- `ord_p(q) = orderNat(q)/e_w`. -/
lemma ordp_tateParameter (t : TateParameter (localCompletion w)) {π : localCompletion w}
    (hπ : IsUniformizer π) :
    ordp k w (t.q : localCompletion w) = ((t.toOrdered hπ).orderNat : ℝ) / ramIdx k w := by
  rw [ordp_eq_of_valued w _ _ (valued_tateParameter_q t hπ)]
  push_cast
  ring

end Uniformizer

end

end Iut
