import Verso
import VersoManual
import VersoBlueprint
import Iut4Sec1Blueprint.TexPrelude

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "1.8. Torsion Points of Elliptic Curves" =>

:::proposition "prop:1.8"
Let $`k` be perfect, let $`\bar k` be an algebraic closure, and write
$`G_k=\Gal(\bar k/k)`.

1. If $`\ell\ge3` is prime and invertible in $`k`, and $`(A,\lambda)` is a
   polarized abelian variety over algebraically closed $`k`, then
   $`\Aut_k(A,\lambda)\to\Aut(A[\ell])` is injective (Serre's criterion).
2. For an elliptic curve $`E_{\bar k}`, there is a natural exact sequence
   $`1\to\Aut_{\bar k}(E)\to\Aut_k(E)\to G_k` with open image $`G_E`, and
   representations $`\rho_n:\Aut_k(E)\to\Aut(E[n])`. The field fixed by
   $`G_E` is the minimal field of definition and is generated by $`j(E)`;
   models over the field fixed by a closed $`H\subseteq G_k` are equivalent to
   sections over $`H`.
3. If $`\Aut_{\bar k}(E)=\{\pm1\}`, then $`\rho_2` factors through $`G_E`.
4. If two descents to $`k` have all their $`\ell`-torsion rational over $`k`
   for invertible prime $`\ell\ge3`, they are isomorphic over $`k`.
5. If $`k` is complete discretely valued and an invertible prime
   $`\ell\ge3` has all $`\ell`-torsion rational, the descended elliptic curve
   has semistable reduction.

   *Clause (v) status: conditional on an explicit `ReductionCertificate`.*
6. If $`2` is invertible, $`G_E=G_k`, the two-torsion action is trivial, and
   $`\Aut_{\bar k}(E)=\{\pm1\}`, then $`E` has a Legendre-form descent. Over a
   complete discretely valued field it becomes semistable after an extension
   of degree at most two; if it has good reduction there, no extension is needed.

   *Clause (vi) status: conditional on an explicit `ReductionCertificate`.*
7. Over a complete discretely valued field, for invertible $`n`, good reduction
   makes the action on $`E[n]` unramified. For bad multiplicative reduction,
   the kernel field is tamely ramified with ramification index dividing $`n`.

   *Clause (vii) status: conditional on an explicit `ReductionCertificate`.*

*Status: conditional/partial; not started.* The unavailable geometric
content of (i)--(vii) is exposed through the fixed `ReductionCertificate` family.
Only separately isolated finite-group and linear-algebra lemmas will be
unconditional.
:::
