/-
Copyright (c) 2026 The iut contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The iut contributors
-/
import Iut.Concrete.ThetaLocalConstruct.Ordp

/-!
# The arithmetic fields of the local theory (taxis #4, #278)

The fields of `Iut.LocalTheory K` about the number field `K` itself, all proved from
Mathlib's theory of Dedekind domains:

* `fiber_finite`: finitely many finite places over each prime (`primesOverFinset`);
* `sum_localDeg`: `∑_{w ∣ p} e_w f_w = [K : ℚ]` (`Ideal.sum_ramification_inertia`);
* `sum_mult`: `∑_{w ∣ ∞} [K_w : ℝ] = [K : ℚ]` (`NumberField.InfinitePlace.sum_mult_eq`);
* `ramified_finite`, `ordDifferent_eq_zero`: the ramified places are those dividing the
  different, which is a nonzero ideal (`dvd_differentIdeal_iff`, `differentIdeal_ne_bot`);
* `ordp_p`, `ordp_mul`: `ord_p(p) = 1` (from `v_𝔭(p) = e_𝔭`, `Ideal.ramificationIdx` being the
  multiplicity of `𝔭` in `p𝓞_K`) and multiplicativity of `ord_p`.
-/

namespace Iut

namespace LocalConstruct

open NumberField IsDedekindDomain WithZero
open scoped WithZero

variable {K : Type*} [Field K] [NumberField K]

/-! ### `ord_p` -/

/-- `ord_p` is multiplicative (`LocalTheory.ordp_mul`). -/
lemma ordp_mul (w : FinitePlace K) (x y : completionAt K w) (hx : x ≠ 0) (hy : y ≠ 0) :
    ordp K w (x * y) = ordp K w x + ordp K w y := by
  unfold ordp
  rw [norm_mul, Real.log_mul (norm_ne_zero_iff.mpr hx) (norm_ne_zero_iff.mpr hy)]
  ring

/-- `v_𝔭(p) = e_𝔭`: the valuation of the residue characteristic in `𝓞_K` is the ramification
index. -/
lemma intValuation_residueChar (w : FinitePlace K) :
    w.maximalIdeal.intValuation (residueChar w : 𝓞 K) = exp (-(ramIdx K w : ℤ)) := by
  have hp : (residueChar w).Prime := residueChar_prime w
  have hp0 : (residueChar w : 𝓞 K) ≠ 0 := by exact_mod_cast hp.ne_zero
  have hspan : Ideal.span {(residueChar w : 𝓞 K)} ≠ 0 := by
    rw [Ne, Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot]
    exact hp0
  have hmap : (Ideal.span {(residueChar w : ℤ)}).map (algebraMap ℤ (𝓞 K)) =
      Ideal.span {(residueChar w : 𝓞 K)} := by
    rw [Ideal.map_span, Set.image_singleton, map_natCast]
  haveI := liesOver_span_residueChar w
  have h : (Associates.mk w.maximalIdeal.asIdeal).count
      (Associates.mk (Ideal.span {(residueChar w : 𝓞 K)})).factors = ramIdx K w := by
    rw [Ideal.count_associates_factors_eq hspan w.maximalIdeal.isPrime w.maximalIdeal.ne_bot]
    unfold ramIdx
    rw [Ideal.IsDedekindDomain.ramificationIdx_eq_normalizedFactors_count
      (Ideal.span {(residueChar w : ℤ)})
      w.maximalIdeal.asIdeal (by rw [hmap]; exact hspan), hmap]
  rw [w.maximalIdeal.intValuation_if_neg hp0, h]

/-- The valuation of the residue characteristic in the completion. -/
lemma valued_residueChar (w : FinitePlace K) :
    Valued.v (algebraMap K (completionAt K w) (residueChar w : K)) = exp (-(ramIdx K w : ℤ)) := by
  have : algebraMap K (completionAt K w) (residueChar w : K) =
      FinitePlace.embedding w.maximalIdeal (algebraMap (𝓞 K) K (residueChar w : 𝓞 K)) := by
    rw [map_natCast (algebraMap (𝓞 K) K)]
    rfl
  rw [this, FinitePlace.embedding_apply, HeightOneSpectrum.valuedAdicCompletion_eq_valuation',
    HeightOneSpectrum.valuation_of_algebraMap, intValuation_residueChar]

/-- `ord_p(p) = 1` (`LocalTheory.ordp_p`). -/
lemma ordp_p (w : FinitePlace K) : ordp K w (algebraMap K _ (residueChar w : K)) = 1 := by
  rw [ordp_eq_of_valued w _ _ (valued_residueChar w)]
  have he : (ramIdx K w : ℝ) ≠ 0 := by exact_mod_cast (ramIdx_pos' w).ne'
  rw [Int.cast_neg, Int.cast_natCast, neg_neg, div_self he]

/-! ### The places over a prime -/

/-- The prime of `ℤ` generated by a prime number. -/
lemma span_prime_ne_bot {p : ℕ} (hp : p.Prime) : Ideal.span {(p : ℤ)} ≠ ⊥ := by
  rw [Ne, Ideal.span_singleton_eq_bot]
  exact_mod_cast hp.ne_zero

/-- The prime of `ℤ` generated by a prime number is maximal. -/
lemma span_prime_isMaximal {p : ℕ} (hp : p.Prime) : (Ideal.span {(p : ℤ)}).IsMaximal := by
  haveI : (Ideal.span {(p : ℤ)}).IsPrime :=
    (Ideal.span_singleton_prime (by exact_mod_cast hp.ne_zero)).2 (Nat.prime_iff_prime_int.1 hp)
  exact IsPrime.to_maximal_ideal (span_prime_ne_bot hp)

/-- A finite place of residue characteristic `p` lies over `(p)`. -/
lemma liesOver_span_of_residueChar {p : ℕ} (w : FinitePlace K) (hw : residueChar w = p) :
    w.maximalIdeal.asIdeal.LiesOver (Ideal.span {(p : ℤ)}) := by
  rw [← hw]
  exact liesOver_span_residueChar w

/-- A finite place over `(p)`, `p` prime, has residue characteristic `p`. -/
lemma residueChar_eq_of_liesOver_span {p : ℕ} (w : FinitePlace K)
    [h : w.maximalIdeal.asIdeal.LiesOver (Ideal.span {(p : ℤ)})] : residueChar w = p := by
  have h1 := under_int_eq w
  rw [← Ideal.over_def w.maximalIdeal.asIdeal (Ideal.span {(p : ℤ)}),
    Ideal.span_singleton_eq_span_singleton] at h1
  have h2 := Int.natAbs_eq_iff_associated.mpr h1
  simpa using h2.symm

/-- **Finitely many finite places over each prime** (`LocalTheory.fiber_finite`). -/
theorem fiber_finite (p : ℕ) : Finite {w : FinitePlace K // residueChar w = p} := by
  by_cases hp : p.Prime
  · have hP0 := span_prime_ne_bot hp
    haveI := span_prime_isMaximal hp
    refine Finite.of_injective (fun w : {w : FinitePlace K // residueChar w = p} =>
      (⟨w.1.maximalIdeal.asIdeal, ?_⟩ :
        IsDedekindDomain.primesOverFinset (Ideal.span {(p : ℤ)}) (𝓞 K))) ?_
    · haveI := liesOver_span_of_residueChar w.1 w.2
      exact (IsDedekindDomain.mem_primesOverFinset_iff hP0 (𝓞 K)).mpr ⟨inferInstance, inferInstance⟩
    · intro w₁ w₂ h
      exact Subtype.ext (FinitePlace.maximalIdeal_injective
        (HeightOneSpectrum.ext (congrArg Subtype.val h)))
  · haveI : IsEmpty {w : FinitePlace K // residueChar w = p} :=
      ⟨fun w => hp (w.2 ▸ residueChar_prime w.1)⟩
    infer_instance

/-- **`∑_{w ∣ p} [K_w : ℚ_p] = [K : ℚ]`** (`LocalTheory.sum_localDeg`). -/
theorem sum_localDeg (p : ℕ) (hp : p.Prime) [Fintype {w : FinitePlace K // residueChar w = p}] :
    ∑ w : {w : FinitePlace K // residueChar w = p}, localDeg K w.1 = Module.finrank ℚ K := by
  classical
  set P : Ideal ℤ := Ideal.span {(p : ℤ)} with hP
  have hP0 : P ≠ ⊥ := span_prime_ne_bot hp
  haveI hmax : P.IsMaximal := span_prime_isMaximal hp
  have hsum := Ideal.sum_ramification_inertia (𝓞 K) ℚ K hP0 (p := P)
  rw [← hsum]
  refine Finset.sum_bij (fun w _ => w.1.maximalIdeal.asIdeal) ?_ ?_ ?_ ?_
  · intro w _
    haveI := liesOver_span_of_residueChar w.1 w.2
    exact (IsDedekindDomain.mem_primesOverFinset_iff hP0 (𝓞 K)).mpr ⟨inferInstance, inferInstance⟩
  · intro w₁ _ w₂ _ h
    exact Subtype.ext (FinitePlace.maximalIdeal_injective (HeightOneSpectrum.ext h))
  · intro Q hQ
    obtain ⟨hprime, hover⟩ := (IsDedekindDomain.mem_primesOverFinset_iff hP0 (𝓞 K)).mp hQ
    have hne : Q ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot hP0 Q
    refine ⟨⟨FinitePlace.mk ⟨Q, hprime, hne⟩, ?_⟩, Finset.mem_univ _, ?_⟩
    · haveI : (FinitePlace.mk ⟨Q, hprime, hne⟩).maximalIdeal.asIdeal.LiesOver P := by
        rw [FinitePlace.maximalIdeal_mk]
        exact hover
      exact residueChar_eq_of_liesOver_span _
    · rw [FinitePlace.maximalIdeal_mk]
  · intro w _
    haveI := liesOver_span_of_residueChar w.1 w.2
    haveI : w.1.maximalIdeal.asIdeal.IsMaximal :=
      w.1.maximalIdeal.isPrime.isMaximal w.1.maximalIdeal.ne_bot
    have hunder : w.1.maximalIdeal.asIdeal.under ℤ = P := by
      rw [under_int_eq, w.2]
    have h1 : ramIdx K w.1 = P.ramificationIdx' w.1.maximalIdeal.asIdeal := by
      have := (Ideal.ramificationIdx'_eq_ramificationIdx _ w.1.maximalIdeal.asIdeal
        (under_int_ne_bot w.1)).symm
      rwa [hunder] at this
    have h2 : inertDeg K w.1 = P.inertiaDeg' w.1.maximalIdeal.asIdeal := by
      haveI : (w.1.maximalIdeal.asIdeal.under ℤ).IsMaximal := under_int_isMaximal w.1
      have := (Ideal.inertiaDeg'_eq_inertiaDeg (w.1.maximalIdeal.asIdeal.under ℤ)
        w.1.maximalIdeal.asIdeal).symm
      rwa [hunder] at this
    unfold localDeg
    rw [h1, h2]

/-- **`∑_{w ∣ ∞} [K_w : ℝ] = [K : ℚ]`** (`LocalTheory.sum_mult`). -/
theorem sum_mult : ∑ w : InfinitePlace K, w.mult = Module.finrank ℚ K :=
  InfinitePlace.sum_mult_eq

/-! ### Ramification and the different -/

section Different

attribute [local instance] FractionRing.liftAlgebra

/-- A place with `e_w = 1` is unramified over `ℤ` (the residue field extension is an
extension of finite fields, hence separable). -/
lemma isUnramifiedAt_of_ramIdx_eq_one (w : FinitePlace K) (h : ramIdx K w = 1) :
    Algebra.IsUnramifiedAt ℤ w.maximalIdeal.asIdeal :=
  (Ideal.ramificationIdx_eq_one_iff (q := w.maximalIdeal.asIdeal) (R := ℤ)).mp h

/-- A place unramified over `ℤ` has `e_w = 1`. -/
lemma ramIdx_eq_one_of_isUnramifiedAt (w : FinitePlace K)
    [Algebra.IsUnramifiedAt ℤ w.maximalIdeal.asIdeal] : ramIdx K w = 1 :=
  Ideal.ramificationIdx_eq_one w.maximalIdeal.asIdeal ℤ

/-- The ramified places divide the different. -/
lemma dvd_differentIdeal_of_ramIdx_ne_one (w : FinitePlace K) (h : ramIdx K w ≠ 1) :
    w.maximalIdeal.asIdeal ∣ differentIdeal ℤ (𝓞 K) := by
  rw [dvd_differentIdeal_iff]
  intro hunr
  exact h (ramIdx_eq_one_of_isUnramifiedAt w)

/-- **Only finitely many finite places are ramified** (`LocalTheory.ramified_finite`). -/
theorem ramified_finite : {w : FinitePlace K | ramIdx K w ≠ 1}.Finite := by
  classical
  have hD : differentIdeal ℤ (𝓞 K) ≠ ⊥ := differentIdeal_ne_bot
  have hfin : ((UniqueFactorizationMonoid.normalizedFactors (differentIdeal ℤ (𝓞 K))).toFinset :
      Set (Ideal (𝓞 K))).Finite := Finset.finite_toSet _
  refine (hfin.preimage (f := fun w : FinitePlace K => w.maximalIdeal.asIdeal) ?_).subset ?_
  · intro w₁ _ w₂ _ h
    exact FinitePlace.maximalIdeal_injective (HeightOneSpectrum.ext h)
  · intro w hw
    rw [Set.mem_preimage, Finset.mem_coe, Multiset.mem_toFinset,
      Ideal.mem_normalizedFactors_iff hD]
    exact ⟨inferInstance, Ideal.le_of_dvd (dvd_differentIdeal_of_ramIdx_ne_one w hw)⟩

/-- **The different exponent vanishes at unramified places**
(`LocalTheory.ordDifferent_eq_zero`). -/
theorem ordDifferent_eq_zero (w : FinitePlace K) (h : ramIdx K w = 1) : ordDifferent K w = 0 := by
  classical
  unfold ordDifferent
  rw [Multiset.count_eq_zero]
  intro hmem
  have hdvd := UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hmem
  rw [dvd_differentIdeal_iff] at hdvd
  exact hdvd (isUnramifiedAt_of_ramIdx_eq_one w h)

end Different

end LocalConstruct

end Iut
