/-
Copyright (c) 2026 The iut contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The iut contributors
-/
import Iut.Concrete.LocalConstruct.LogShell
import Iut.Concrete.LocalConstruct.ArchLogShell
import Iut.Concrete.LocalConstruct.Hull
import Iut.Concrete.LocalConstruct.Prop14

/-!
# The concrete local theory (taxis #4, #278)

This file assembles the constructions of `Iut/Concrete/LocalConstruct/*` into a term
`concreteLocalTheory K : Iut.LocalTheory K`. Every field of `LocalTheory` is proved
from the construction; no propositional input remains.

* `(R_I)^∼ ⊆ 𝓘_I` (`integral_subset_logShell`, `LogShell.lean`; the log-shell of a packet is
  the `(R_I)^∼`-module generated by the tensor product of the log-shells of the factors).
* Least hull regions `a·(R_I)^∼` containing an admissible region at a prime
  (`exists_leastHull_finite`, `Hull.lean`; componentwise in the residue fields of the packet,
  `ResidueField.lean`); the archimedean counterpart `exists_leastHull_infinite` is in
  `Admissible.lean`.
* IUT IV, Proposition 1.4(iii) (`prop14iii_of_isOver`, `Prop14.lean`): the hull region is
  `p^{⌊ord_p x⌋}·(R_I)^∼`.
-/

namespace Iut

namespace LocalConstruct

open NumberField
open scoped Pointwise

universe u

variable (K : Type u) [Field K] [NumberField K]

/-- **The log-shell of a packet**, uniformly in the rational place (`LocalTheory.logShell`):
the `(R_I)^∼`-module generated by `⊗_j 𝓘_{c j}` at a prime, `π^{|I|}·B_I` at the archimedean
place. -/
noncomputable def logShellAt {ι : Type} [Fintype ι] :
    ∀ (vQ : RationalPlace) (c : ι → Place K), Set (Tensor K vQ c)
  | .finite p, c => logShell p c
  | .infinite, c => archLogShell c

variable {K}

lemma logShellAt_finite {ι : Type} [Fintype ι] (p : Nat.Primes) (c : ι → Place K) :
    logShellAt K (.finite p) c = logShell p c := rfl

lemma logShellAt_infinite {ι : Type} [Fintype ι] (c : ι → Place K) :
    logShellAt K .infinite c = archLogShell c := rfl

variable (K)


/-- **The concrete local theory**: `Iut.LocalTheory K` from the constructions of
`Iut/Concrete/LocalConstruct/*`, with no residual input. -/
noncomputable def concreteLocalTheory : LocalTheory.{u, u} K where
  toLocalTensor := concreteLocalTensor (K := K)
  residueChar_prime := residueChar_prime
  fiber_finite := fiber_finite
  ramified_finite := ramified_finite
  localDeg_pos := localDeg_pos
  ramIdx_pos := ramIdx_pos
  ordDifferent_eq_zero := ordDifferent_eq_zero
  sum_localDeg p hp _ := sum_localDeg p hp
  sum_mult := sum_mult
  ordp_p := ordp_p
  ordp_mul := ordp_mul
  incl := incl
  isUnit_incl := isUnit_incl
  integral := integralAt
  one_mem_integral := one_mem_integralAt
  smul_integral_subset := smul_integral_subset_of_ordp
  logShell := logShellAt K
  logShell_relCompact vQ c := by
    cases vQ with
    | finite p => exact isCompact_closure_logShell p c
    | infinite => exact isCompact_closure_archLogShell c
  integral_subset_logShell := integral_subset_logShell
  logShell_eq_integral := logShell_eq_integral_of_unramified
  componentVol := componentVol
  componentVol_integral vQ c := componentVol_integral
  componentVol_prime_preimage p c hc U hU := componentVol_prime_preimage_of_admissible p hc hU
  componentVol_mono vQ c := componentVol_mono
  componentVol_arch_scale c := componentVol_arch_scale
  admissible := admissible
  admissible_nonempty vQ c U := admissible_nonempty
  admissible_relCompact vQ c U := admissible_relCompact
  integral_admissible vQ c := integral_admissible
  smul_integral_admissible vQ c := smul_integral_admissible
  exists_leastHull p c U hU := exists_leastHull_finite p c hU
  exists_leastHull_infinite c U hU := exists_leastHull_infinite c hU
  smul_integral_infinite_mono c := smul_integralAt_infinite_mono c
  indAut := indAut
  id_mem_indAut := id_mem_indAut
  indAut_logShell vQ c := by
    cases vQ with
    | finite p => exact indAut_logShell p c
    | infinite => exact indAut_archLogShell c
  theta_admissible := theta_admissible
  thetaShell_admissible vQ c := by
    cases vQ with
    | finite p => exact thetaShell_admissible p c
    | infinite => exact thetaShell_admissible_infinite c
  prop14_iii p c hc := prop14iii_of_isOver p c hc
  prop14_iv := prop14_iv
  prop15 := prop15

end LocalConstruct

end Iut
